import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const Backoffice: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title> Backoffice </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Backoffice</h1>
      </div>
    </div>
  )
}

export default Backoffice
